In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [16]:
df= pd.read_csv("C:\\Users\\AtulKumar\\Downloads\\CAR_DETAILS_FROM_CAR_DEKHO.csv")
new=df.head(5)
new

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [19]:
dm=pd.get_dummies(new.name)
dm

Datsun RediGO T Option  Honda Amaze VX i-DTEC  Hyundai Verna 1.6 SX  \
0                       0                      0                     0   
1                       0                      0                     0   
2                       0                      0                     1   
3                       1                      0                     0   
4                       0                      1                     0   

   Maruti 800 AC  Maruti Wagon R LXI Minor  
0              1                         0  
1              0                         1  
2              0                         0  
3              0                         0  
4              0                         0

In [24]:
concatData= pd.concat([new,dm],axis=1)
concatData

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  Datsun RediGO T Option  \
0  Individual       Manual   First Owner                       0   
1  Individual       Manual   First Owner                       0   
2  Individual       Manual   First Owner                       0   
3  Individual       Manual   First Owner                       1   
4  Individual       Manual  Second Owner                       0   

   Honda Amaze VX i-DTEC  Hyundai Verna 1.6 SX  Maruti 800 AC  \
0                      0                     0              1   
1                      0                     0              0   
2                      0                     1              0   
3                      0                     0              0   
4                      1                     0              0   

   Maruti Wagon R LXI Minor  
0                         0  
1                         1  
2                         0  
3                         0  
4                         0

In [30]:
final_data=concatData.drop(['name','fuel','seller_type','transmission','owner'],axis=1)
final_data

year  selling_price  km_driven  Datsun RediGO T Option  \
0  2007          60000      70000                       0   
1  2007         135000      50000                       0   
2  2012         600000     100000                       0   
3  2017         250000      46000                       1   
4  2014         450000     141000                       0   

   Honda Amaze VX i-DTEC  Hyundai Verna 1.6 SX  Maruti 800 AC  \
0                      0                     0              1   
1                      0                     0              0   
2                      0                     1              0   
3                      0                     0              0   
4                      1                     0              0   

   Maruti Wagon R LXI Minor  
0                         0  
1                         1  
2                         0  
3                         0  
4                         0

In [40]:
reg = linear_model.LinearRegression()
x = final_data.drop('selling_price',axis=1)
x

year  km_driven  Datsun RediGO T Option  Honda Amaze VX i-DTEC  \
0  2007      70000                       0                      0   
1  2007      50000                       0                      0   
2  2012     100000                       0                      0   
3  2017      46000                       1                      0   
4  2014     141000                       0                      1   

   Hyundai Verna 1.6 SX  Maruti 800 AC  Maruti Wagon R LXI Minor  
0                     0              1                         0  
1                     0              0                         1  
2                     1              0                         0  
3                     0              0                         0  
4                     0              0                         0

In [43]:
y= final_data.selling_price
y

0     60000
1    135000
2    600000
3    250000
4    450000
Name: selling_price, dtype: int64

In [44]:
reg.fit(x,y)

LinearRegression()

In [47]:
Hundai_verna=reg.predict([[2020,50000,0,0,1,0,0]])
Hundai_verna

C:\Users\AtulKumar\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([589626.2717346])

In [49]:
Datsun=reg.predict([[2020,50000,1,0,0,0,0]])
Datsun

C:\Users\AtulKumar\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([322774.5897235])

In [48]:
Honda_Amaze=reg.predict([[2020,50000,0,1,0,0,0]])
Honda_Amaze

C:\Users\AtulKumar\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([261931.19947031])